import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { GoogleAdsenseContainer } from "../components/GoogleAdsenseContainer";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1103570262283389"
          crossOrigin="anonymous"
        ></script>
      </Head>

      <div className={styles.row}>
        <div className={styles.body}>Lorem</div>
        <div className={styles.side}>
          <GoogleAdsenseContainer
            client="ca-pub-1103570262283389"
            slot="1884465413"
          />
        </div>
      </div>
      <GoogleAdsenseContainer
        client="ca-pub-1103570262283389"
        slot="7069058074"
      />
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
